### ISSUE TITLE
any suggestion on how to generate aggregate submatrix plot

### ISSUE THREAD

**Issue by yxian9** [koustav-pal/HiCBricks#16]
Thanks for providing this efficient tool. 

I wonder is it possible to plot aggregated Hi-C sub-matrices of a specified list of positions, such as sub-contacts around some histone peaks?

similar function as this one. 
https://hicexplorer.readthedocs.io/en/latest/content/tools/hicAggregateContacts.html#hicaggregatecontacts

thank you!

**Comment by koustav-pal** [comment]
Hi @yuxuth,

Many apologies for the delayed response. Unfortunately there is no simple solution for this particular feature in the current package. You can of course retrieve the aggregated data values using functions such as Brick_get_vector_values and Brick_get_matrix_within_coords. But, There are no functions for such plots.

The aggregate maps are planned for a future update. There are many different scaling methods that are used in literature, which makes it difficult for me to provide a one function fits all solution for this problem.

**Comment by yxian9** [comment]
Thank you for your advice! 
Best, Yu
