### ISSUE TITLE
Package failing on Bioconductor

### ISSUE THREAD

**Issue by Kayla-Morrell** [koustav-pal/HiCBricks#20]
Hello Koustav,
 
The next Bioconductor release 3.15 is scheduled for April 27th. Commits to the
current 3.14 release should be made by April 8th and the last day to commit to
the devel branch is April 22nd. We like to make an effort to have all
Bioconductor packages building and checking without ERROR or TIMEOUT in both
release and devel versions. For some reason the email I sent was undeliverable 
which is why I'm opening an issue on the GitHub.
 
Currently your package is producing an ERROR across all builders in the release
version of Bioconductor. Could you please investigate the error as soon as
possible?
 
Release version -
https://bioconductor.org/checkResults/3.14/bioc-LATEST/HiCBricks/
 
If you need any assistance please feel free to ask questions at
[bioc-devel@r-project.org](mailto:bioc-devel@r-project.org).
 
Thank you,
Kayla

**Comment by decarlin** [comment]
bump

**Comment by koustav-pal** [comment]
Hi, 

Many apologies. I did not receive any notification about this error and only now checked the package.

**Comment by koustav-pal** [comment]
Hi,

I believe this issue has been rectified with Bioconductor version 3.15.

Can you please comment, that its all good.
